name: check

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: Kesin11/actions-timeline@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Show environment
        run: pwd; ls -la; deno --version
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run: deno task check
